# roles/system-security/firewall/handlers/main.yml
---
- name: Reload ufw
  become: yes
  community.general.ufw:
    state: reloaded
  when: not ansible_check_mode  # 在 check 模式下跳过

- name: Restart ufw
  become: yes
  ansible.builtin.service:
    name: ufw
    state: restarted
  when: not ansible_check_mode  # 在 check 模式下跳过

