auroraops_roles:
  personalization:
    user_management: true
  system:
    base: true
    benchmark: false
    fail2ban: true
    firewall: true
    init: true
    journald: true
    limits: true
    logrotate: true
    python_environment: true
    reinstall: false
    ssh: true
    swap: true
    sysctl: true
    systemd_priority: true
    unattended_upgrades: true
    zerotier: false
    zram: true
