---
fail2ban_fact_path: /etc/ansible/facts.d/fail2ban.fact
fail2ban_package_name: fail2ban
fail2ban_service_name: fail2ban
fail2ban_jail_local_path: /etc/fail2ban/jail.local

# 角色内部默认值，通常不建议直接修改，而是通过 group_vars/host_vars 覆盖
fail2ban_bantime: 1h
fail2ban_findtime: 10m
fail2ban_maxretry: 5
fail2ban_ignoreip:
  - 127.0.0.1/8
